language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
before_script:
  -
script:
  - pytest
  - flake8 cmdbox
  - coverage run manage.py test --settings=cmdbox.tests_settings
after_success:
  - coveralls

  notifications:
    slack: andela:4Y68W1U2jFTfv3i7LrVVkFzS