language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"

before_script:
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - coveralls

notifications:
  slack: andela:4Y68W1U2jFTfv3i7LrVVkFzS
  webhooks: https://coveralls.io/webhook?repo_token=RT2CHqilsAIb8tIYDvllBKaA2fvxyIvqh